### PR TITLE
use the simde header library for non-x86 compatability

### PR DESCRIPTION
**Pull request by mr-c**
Hello, this is a patch that we use for the Debian package of pbcopper to enable building on non-x86 systems like arm64, ppc64el, and s390x

### CODE REVIEW

**Comment by armintoepfer** [comment]
Thank you. We'll discuss internally and then likely cherry-pick your commit!

**Comment by armintoepfer** [comment]
Hey @mr-c,

this isn't working on Apple Clang: `clang 11.0.0 "Apple clang version 11.0.0 (clang-1100.0.33.17)")`

```
../src/third-party/simde-no-tests/x86/sse2.h:4872:5: error: 'diagnose_if' attribute expression never produces a constant expression
    SIMDE_REQUIRE_CONSTANT_RANGE(imm8, 0, 255)
    ^
../src/third-party/simde-no-tests/x86/../simde-common.h:176:5: note: expanded from macro 'SIMDE_REQUIRE_CONSTANT_RANGE'
    SIMDE_REQUIRE_CONSTANT(arg)                     \
    ^
../src/third-party/simde-no-tests/x86/../simde-common.h:163:5: note: expanded from macro 'SIMDE_REQUIRE_CONSTANT'
    HEDLEY_REQUIRE_MSG(SIMDE_CHECK_CONSTANT_(arg), "`" #arg "' must be constant")
    ^
../src/third-party/simde-no-tests/hedley.h:1744:24: note: expanded from macro 'HEDLEY_REQUIRE_MSG'
        __attribute__((diagnose_if(!(expr), msg, "error"))) HEDLEY_DIAGNOSTIC_POP
                       ^
../src/third-party/simde-no-tests/x86/sse2.h:4872:5: note: subexpression not valid in a constant expression
../src/third-party/simde-no-tests/x86/../simde-common.h:176:5: note: expanded from macro 'SIMDE_REQUIRE_CONSTANT_RANGE'
    SIMDE_REQUIRE_CONSTANT(arg)                     \
    ^
../src/third-party/simde-no-tests/x86/../simde-common.h:163:24: note: expanded from macro 'SIMDE_REQUIRE_CONSTANT'
    HEDLEY_REQUIRE_MSG(SIMDE_CHECK_CONSTANT_(arg), "`" #arg "' must be constant")
                       ^
../src/third-party/simde-no-tests/x86/../simde-common.h:154:38: note: expanded from macro 'SIMDE_CHECK_CONSTANT_'
#define SIMDE_CHECK_CONSTANT_(expr) (__builtin_constant_p(expr))
```

**Comment by mr-c** [comment]
@armintoepfer Huh! Okay, I've reported it upstream https://github.com/simd-everywhere/simde/issues/470
Could you add some macOS CI to this PR/repo so I can check myself?

**Comment by mr-c** [comment]
@armintoepfer I've updated the git submodule to be up to date with https://github.com/simd-everywhere/simde/commit/e5b5b7db97892a378fa6d2714b299791c4c5eb10 which should fix the clang 11 issue ; thanks again for the report!

**Comment by armintoepfer** [comment]
Thank you. I'll patch it internally and try again as time allows.

**Comment by mr-c** [comment]
@armintoepfer Thanks, let me know what I can do to help. I've refreshed this PR to use the latest regular release of SIMDe (v0.6.0)

**Comment by armintoepfer** [comment]
We can't merge this right now, as each and every project relies on pbcopper and thus we'd need to add simde as a dependency to every project. We will consider adding this once we also target ARM. The feature branch is ready to merge internally, when we decide to pull the trigger.

**Comment by armintoepfer** [comment]
Only took me half a year, but it's done :)

**Comment by mr-c** [comment]
Woohoo! When can we expect a new release?

**Comment by armintoepfer** [comment]
As in tagging a new release? @derekwbarnett it should be fine if we cut 1.9.0 now?

**Comment by derekwbarnett** [comment]
Yeah, we can bump it.

**Comment by armintoepfer** [comment]
https://github.com/PacificBiosciences/pbcopper/releases/tag/v1.9.0
